### ISSUE TITLE
Мод русификатора не качает последние изменения

### ISSUE THREAD

**Issue by Valianton** [DreamSworK/Wakfu-Mod-Installer#2]
В описании программы говорится, что

> Установка всех модов и плагинов полностью происходит из веб репозитория. При установке скачиваются самые последние версии модов и плагинов.
Простое добавление, удаление и обновление существующих модов

Но это не совсем так, последняя версия не скачивается

**Comment by Valianton** [comment]
Могу предположить, что так происходит из-за того, что вы качаете файлы русификатора с https://github.com/DreamSworK/Wakfu-Translate/commits/master.

**Comment by Valianton** [comment]
А недавно были добавлены обновления в русификатор, так что вам тоже нужно обновить свою ветку, спасибо.

**Comment by DreamSworK** [comment]
Качает из этого же репозитория https://github.com/DreamSworK/Wakfu-Mod-Installer/ но только из папки с модом. Если вы сможете в своём репозитории создать у себя такую же папку (в виде мода) https://github.com/DreamSworK/Wakfu-Mod-Installer/tree/master/packages/wakfu.mod.rus/data/rus и в ней выкладывать релиз и последние изменения. Я тогда просто добавлю вашу папку как *git субмодуль* для экспорта напрямую из вашего репозитория в мой это папки.

**Comment by DreamSworK** [comment]
Если в вашем репозитории будет папка с модом будет проще обновлять, так как в том виде как сейчас, нужно менять вручную, то есть приводить в формат мода.

**Comment by DreamSworK** [comment]
Обновил русификатор.
На досуге изучите как устроена эта папка: https://github.com/DreamSworK/Wakfu-Mod-Installer/tree/master/packages/wakfu.mod.rus В папке *data* сам русификатор * в подпапке *rus* В папке *meta* версия, дата, описание и так далее, эта информация показывается в апдейтере. Там всё просто, если сможете создать у себя такую же папку с модом, я смогу настроить либо экспорт, либо напрямую чтобы скачивало у вас.

**Comment by Valianton** [comment]
Вот, посмотрите, https://github.com/Valianton/Wakfu-Translate/tree/master/wakfu.mod.rus. Все правильно?

**Comment by DreamSworK** [comment]
Да, всё правильно, формат правильный. Но единственное версия должна быть выше предыдущей, иначе если версия номером ниже, это считается как устаревшее обновление. То есть при обновлении проверяется наличие версии выше номером. А я изначально просто за номер версии взял _**последний номер комита**_ из вашего репозитория. То есть если 1.6.0 комита, я просто назвал 1.6.0 то есть следующая версия должна быть выше этого числа, например 1.6.1 или 1.6.2 или 1.7.0 или 2.0.0 смысл понятен думаю.

**Comment by DreamSworK** [comment]
Вы сейчас поставили версию ниже 1.1.0

**Comment by Valianton** [comment]
Ок, все ясно. Спасибо.

**Comment by Valianton** [comment]
Я же правильно понял, что сейчас, если я обновлю репозиторий, то у ребят, что пользуются этой программой, тоже все обновится? При условии, что я поставлю версию выше?

**Comment by DreamSworK** [comment]
Пока я должен настроить экспорт этой папки в свой репозиторий, плюс так же обновлять свой репозиторий когда ваша папка поменялась, но это очень быстро, так как мне менять ничего не надо. Позже через время сделаю чтобы скачивалось прямо от вас, но это будет позже.

**Comment by DreamSworK** [comment]
Привет, ещё раз. Возникла небольшая трудность, _**git**_ не предусмотрена возможность делать сабмодуль ссылаясь на подпапку внутри другого репозитория, только на весь репозиторий целиком от корня. То есть если я сейчас добавлю твой репозиторий у себя в подпапку wakfu.mod.rus как сабмодуль, получается неправильная ссылка wakfu.mod.rus/wakfu.mod.rus то есть дублируется название папки. Вообщем нужно подправить путь немного у тебя, чтобы просто у тебя было: **_https://github.com/Valianton/Wakfu-Translate/data_** и **_https://github.com/Valianton/Wakfu-Translate/meta_** (то есть папки _**data и meta в корне**_ репозитория, без папки wakfu.mod.rus)

**Comment by Valianton** [comment]
Исправлено

**Comment by DreamSworK** [comment]
Да, хотел добавить. Что для обновления руссификатора достаточно запустить _**Wakfu Mod Installer**_ (после установки его появляется опция "Update mods") На данный момент, пока так реализован процесс обновлений. То есть обновление есть, но оно не автоматическое, пользователь сам должен проверять.
![update1](https://cloud.githubusercontent.com/assets/375156/25785311/c15fb3a2-3353-11e7-8b28-38eb57cb8570.jpg)
![update2](https://cloud.githubusercontent.com/assets/375156/25785312/c163fa8e-3353-11e7-8806-2a5e919a0f9a.jpg)
