### ISSUE TITLE
Мод на поддержук кириллицы в чате

### ISSUE THREAD

**Issue by Valianton** [DreamSworK/Wakfu-Mod-Installer#3]
Привет, наверняка найдутся пользователи фанаты игры, которые не захотят русифицировать игру, но не отказались бы от поддержки кирилицы в чате. Было бы не плохо добавить и этот мод. В моем решении это тоже есть, путем добавления конкретных шрифтов. Вы можете сделать такой мод? Он как бы является дочерним к моду русификатора, но он самостоятелен и по сути может работать и без родителя!

**Comment by DreamSworK** [comment]
Привет, да сделаю.

**Comment by Valianton** [comment]
Еще вопрос, не по этой теме, но все же. Можно сделать так, чтобы при обновлении мода в программе так же было указано, помимо новый версии, и новые изменения, которые сопровождают эту версию?

**Comment by DreamSworK** [comment]
Да, я думал об этом несколько дней назад. Но пока не решил как и где это будет показываться. Так как при обновлении скорее нужно показывать не изменения в последней версии, а весь ченжлог изменений, так обновление может происходить не с одной версии на другую по порядку, а скажем минуя несколько версий. Да и вообще возможно при установке с нуля, тоже было бы неплохо показывать историю изменений. Вообщем пока не ясно где и как и что будет показываться, может быть лучше даже сделать чтобы показывалось в с самом апдейтере типа "иформацию о моде и его историю и последнюю установленную версию" при запуске игры уже, а не в инсталляторе.

**Comment by DreamSworK** [comment]
Добавил данный мод. **_Mod Russian Chat 1.0.0_** Только добавляет поддержку кириллицы, больше ничего.
