### ISSUE TITLE
Antegros - не работает русификатор

### ISSUE THREAD

**Issue by Valianton** [DreamSworK/Wakfu-Mod-Installer#5]
Antegros Linux-64, gnome 3.24.2, не работает русификатор, как говорит пользователь [ubuntux](https://vk.com/ubuntux), мод ставиться, в игру входит, но вместо текста, там только текст типа 

> !content.42.100!

В смысле даже английского текста нет, как и русского, это может означать, что нет файла texts_en.properties, либо он не подгрузился.

**Comment by DreamSworK** [comment]
Без логов трудно чем-то помочь. Надо смотреть откуда идёт загрузка файлов и т.д. Вероятней всего не корректно определилась папка пользователя _**home directory**_, в которой загрузчик хранит настройки и временные файлы.

**Comment by ubuntuxby** [comment]
какие именно логи нужны?

**Comment by DreamSworK** [comment]
Нужны логи работы самой игры, но на каждой системе они хранятся в разных местах. На чаще всего в папке пользователя `.local/share/data/Ankama/Wakfu/game/logs/wakfu.log` или просто поищите `wakfu.log` в системе.

В принципе сам загрузчик модов совместим с большинством Linux дистрибутивов, но проверить на каждом конечно возможности нет. Возможно будет проще, когда будет время, мне самому просто поставить на виртуалке данный дистрибутив и проверить что к чему.

**Comment by ubuntuxby** [comment]
Как Вам удобнее положить лог, на пасту или файлом?

**Comment by DreamSworK** [comment]
Лучше файлом, к сообщению прикрепите.

**Comment by ubuntuxby** [comment]
сделал
[logs.zip](https://github.com/DreamSworK/Wakfu-Mod-Installer/files/1016147/logs.zip)

**Comment by ubuntuxby** [comment]
фууух
решил проблему
![2017-05-20 15-27-20](https://cloud.githubusercontent.com/assets/18498236/26275751/ddfb9d1a-3d70-11e7-87e2-f3b16ca4085f.png)
всего-то нужно было скопировать файлик i18n_ru.jar в i18n_en.jar по пути ~/.config/Ankama/
затем открыть файл i18n_en.jar и переименовать в нём файл texts_ru.properties в texts_en.properties и всё заработало, есть как английский текст так и руссификация. Спасибо!

**Comment by Valianton** [comment]
Ну, это похоже на какое-то костыльное решение =)

**Comment by DreamSworK** [comment]
Проблема в том, что по какой-то причине не заменяется язык, должен передаваться параметр `ru` , а передаётся параметр по умолчанию `en`. В результате игра ищет `en архив`. Хотя в тоже самое время остальные параметры передаются нормально. Скиньте содержимое папки `~/.config/Ankama` всё кроме *.jar архивов.

**Comment by ubuntuxby** [comment]
[configankama.zip](https://github.com/DreamSworK/Wakfu-Mod-Installer/files/1016165/configankama.zip)

**Comment by ubuntuxby** [comment]
пусть костыльное, но всё-же можно поиграть))

**Comment by DreamSworK** [comment]
Причина проблемы в принципе понятна. Она заключается в том, что файл конфигурации `wakfu.ici` используется за 2016 год, хотя на всех других платформах используется файл за 2017 год. Эта проблема _**апдейтера Анкамы**_ в том, что он для данной платформы скачивает устаревший файл. Сейчас дам небольшой фикс.

**Comment by DreamSworK** [comment]
Найдите файл `rus.ini` в папке с модом русификации и замените первые строчки:

> mods/rus/rus.ini

_**До замены:**_
```
[modifications]
1\file=wakfu.ici
1\before=launcher.options += \"${i18n.lang}\"
1\after=launcher.options += \"ru\"
1\type=settings
```

_**После замены должно быть:**_

```
[modifications]
1\file=wakfu.ici
1\before=\"-L\", \"${i18n.lang}\",
1\after=\"-L\", \"ru\",
1\type=settings
```

**Comment by ubuntuxby** [comment]
заменил по пути:
```
viiv@xxx ..m/steamapps/common/Wakfu/game/mods/rus % pwd
/home/viiv/.local/share/Steam/steamapps/common/Wakfu/game/mods/rus

```
Но это не помогло...

**Comment by DreamSworK** [comment]
Очистите полностью папку `~/.config/Ankama` и после запуска игры, откройте файл `~/.config/Ankama/wakfu.ici` и посмотрите заменяются ли настройки в строке _**358**_ должно быть `"-L", "ru"`, а не `"-L", "${i18n.lang}"`.

**Comment by ubuntuxby** [comment]
после проделанной операции в строке 358 файла ~/.config/Ankama/wakfu.ici  имеется следующая картина: 
`"-L", "${i18n.lang}",`

**Comment by DreamSworK** [comment]
Я уже установил Antegros, сейчас посмотрю что там к чему, в чём проблема, так будет проще.

**Comment by DreamSworK** [comment]
Вообщем-то очень странно, установил "всё прошло без заминки", инсталлятор всё верно определил, установил и всё корректно работает.
![antergos](https://cloud.githubusercontent.com/assets/375156/26308144/fe334afa-3ec5-11e7-98a4-b789492b2e6d.jpg)

**Comment by DreamSworK** [comment]
Такое ощущение что у вас почему-то некоторые файлы из "устаревшей версии", тот же wakfu.ici у вас почему-то за 2016 год, а у меня скачался при установке новый за 2017 год, думаю из-за этого проблема. Воозможно апдейтер не может обновить какаие-то файлы. Попробуйте полностью удалить все папки от игры и установить заново. Удаление из Стима не достаточно, так как он только удаляет сам апдейтер, нужно полностью удалить бабки с игрой после удаление из Стима и почистить всё.

**Comment by DreamSworK** [comment]
Единственное заметил что при установке у меня постоянно апдейтер выкидывал несколько раз ошибки, что не может перезаписать некоторые файлы, приходилось несколько раз перезапускать, но в конце концов игра установилась нормально со Стима.

**Comment by DreamSworK** [comment]
Если и есть проблема, то она где-то в настройках системы, а не в плагине, так как после проверки у меня всё работало прекрасно.
Как вариант, можете попробовать установить последнюю версию, там изменён механизм смены языка.
